[package]
name = "kapture-tap-receiver"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "kapture-tap-receiver"
path = "src/main.rs"

[dependencies]
tokio = { version = "1", features = ["rt-multi-thread", "macros", "net", "io-util", "signal", "time", "sync"] }

[profile.release]
lto = "thin"
codegen-units = 1
